[build]
  command = "npm run build"
  publish = ".next"
  node_version = "18"

[template]
  incoming-hooks = ["WixBookings"]

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = "Wix Headless Client ID" 